Feature 33 nav item settings
nology-tech/Sable-client-project pull request #15
Opened 2023-02-21 14:26 UTC by Joshua-Tucker

2023-02-21 15:15 UTC, TristanPere requested changes
Waiting on discussed changes

2023-02-22 09:24 UTC, TristanPere requested changes
Looks great, just need the font family in typography.scss uncommented

2023-02-22 09:24 UTC, TristanPere commented on src/styles/base/_typography.scss
> +
Needs to be commented back in.

2023-02-22 09:33 UTC, TristanPere approved these changes

2023-02-22 09:33 UTC, olirob93 approved these changes

2023-02-22 09:34 UTC, merged