55 staff page
nology-tech/Sable-client-project pull request #22
Opened 2023-02-22 15:39 UTC by tomas-trls

Added a staff page, and an overview staff page component, and populated it with dummy booking data cards. 
Created test for the Overview Staff Page Container.
Styled the page based on the Figma designs. 
:shipit:

2023-02-22 16:52 UTC, TristanPere requested changes
Make changes discussed

2023-02-22 16:52 UTC, TristanPere commented on src/components/DataCard/DataCard.scss
>  @media screen and (max-width: $desktop-breakpoint) {
change to tablet break point

2023-02-23 10:42 UTC, TristanPere requested changes
Heading is in main branch so can now be incorporated.

2023-02-23 10:42 UTC, TristanPere commented on src/containers/StaffOverview/StaffOverview.jsx
> +        <DataCard cardType="booking" cardObject={testObject} />
I git why you did this and it looks great just remove in final PR

2023-02-23 10:42 UTC, TristanPere commented on src/containers/StaffOverview/StaffOverview.jsx
> +    courseName: "whatever",
Great test data, just remove in final PR

2023-02-23 12:28 UTC, olirob93 approved these changes

2023-02-23 12:28 UTC, TristanPere approved these changes

2023-02-23 12:28 UTC, merged