Feature 23 page header
nology-tech/Sable-client-project pull request #23
Opened 2023-02-22 15:40 UTC by BeckyRushton

Completed header ticket with mobile and desktop stylings.

Testing notes below:

When you want to change the options in the dropdown menu give it you desired options in optionsArr prop.

Examples

HeadingOnlyJSX - empty optionsArr needs to be included
<PageHeader
heading="Home"
headerType="headingOnly"
optionsArr={[]}
/>

HeadingButtonJSX - empty optionsArr needs to be included
<PageHeader
heading="resources"
text="edit"
headerType="headingButton"
optionsArr={[]}
/>

HeadingButtonDropdownJSX
<PageHeader
heading="staff"
text="edit"
headerType="headingButton"
optionsArr={[option 1, option 2]}
/>

2023-02-22 15:44 UTC, BeckyRushton commented
HeadingOnlyJSX - empty optionsArr needs to be included
<PageHeader
heading="Home"
headerType="headingOnly"
optionsArr={[]}
/>

HeadingButtonJSX - empty optionsArr needs to be included
<PageHeader
heading="resources"
text="edit"
headerType="headingButton"
optionsArr={[]}
/>

HeadingButtonDropdownJSX
<PageHeader
heading="staff"
text="edit"
headerType="headingButton"
optionsArr={[option 1, option 2]}
/>

2023-02-22 16:14 UTC, TristanPere requested changes
All the functionality looks amazing, just some refactoring to be done to stop the options array needing to be declared when it isn't used and then some styling to bring it closer to the figma

2023-02-22 16:14 UTC, TristanPere commented on src/components/PageHeader/PageHeader.jsx
> +  const HeadingButtonDropdownJSX = () => (
Change this function to include above map. Change parenthesises to {    }  so that is a function and then set the current html into a return ( ... )

2023-02-22 16:14 UTC, TristanPere commented on src/components/PageHeader/PageHeader.jsx
> +  });
Move this into the HeadingButtonDropdownJSX function.

2023-02-22 16:14 UTC, TristanPere commented on src/components/PageHeader/PageHeader.scss
> +@media screen and (min-width: 1440px) {
change min-width to 768px

2023-02-23 09:25 UTC, TristanPere requested changes
Looking great still, only a few minor changes. The header with the drop down box is adding height to the header. All headers need to be the same height regardless of button, text, and dropdown.

2023-02-23 10:16 UTC, navina321 commented
get test data from readme

2023-02-23 10:31 UTC, TristanPere approved these changes

2023-02-23 10:37 UTC, olirob93 approved these changes

2023-02-23 10:37 UTC, merged