Feature 21 client details card
nology-tech/Sable-client-project pull request #30
Opened 2023-02-23 16:39 UTC by DexterFreeman

Created two components: BookingDetailsCard, ContactDetailsCard.
Tested both containers, also included mock data for both components in the test files. 
Styled according to Figma design. 
:shipit:

2023-02-23 16:53 UTC, TristanPere requested changes
Looking strong. More nit-picks this time with sizing and colours. also there is a components folder in home that you made. can that be deleted please. Also please include the testing data you used in the next PR, if you used data from mockData.js please say.

2023-02-23 16:53 UTC, TristanPere commented on src/components/ContactDetailsCard/ContactDetailsCard.jsx
> +  const {cardObject} = props
Put Props inline

2023-02-23 16:53 UTC, TristanPere commented on src/components/BookingDetailsCard/BookingDetailsCard.jsx
> +   const {cardObject} = props;
Destructure props inline, move _line 5_ into _line 4_

2023-02-23 16:53 UTC, TristanPere commented on src/components/BookingDetailsCard/BookingDetailsCard.scss
> +    background-color: #FFFFFF;
Round Height and Width to nearest 5px

2023-02-23 16:53 UTC, TristanPere commented on src/components/BookingDetailsCard/BookingDetailsCard.scss
> +    background-color: #FFFFFF;
Use the variables for colouring

2023-02-23 16:53 UTC, TristanPere commented on src/components/BookingDetailsCard/BookingDetailsCard.scss
> +        color: #102B3F;
use variables colouring

2023-02-23 16:53 UTC, TristanPere commented on src/components/BookingDetailsCard/BookingDetailsCard.scss
> +        color: #102B3F;
use variable for colouring

2023-02-23 16:53 UTC, TristanPere commented on src/components/BookingDetailsCard/BookingDetailsCard.scss
> +        color: #95ACCB;
use variables for colouring

2023-02-23 16:53 UTC, TristanPere commented on src/components/ContactDetailsCard/ContactDetailsCard.scss
> +    background-color: #FFFFFF;
Same notes as before

2023-02-24 11:15 UTC, TristanPere requested changes

2023-02-24 11:15 UTC, TristanPere commented on src/components/BookingDetailsCard/BookingDetailsCard.scss
> +    background-color: $color-black;
Needs to be white not black

2023-02-24 11:20 UTC, TristanPere approved these changes

2023-02-24 11:20 UTC, olirob93 approved these changes

2023-02-24 12:26 UTC, merged