Feature 72 settings page
nology-tech/Sable-client-project pull request #37
Opened 2023-02-27 14:35 UTC by navina321

completed settings page with testing

2023-02-27 14:55 UTC, TristanPere requested changes
The page looks great and matches figma well. However, the repo tests are failing as there is a use of start instead of flex start somewhere in your code (look at the PR conversation for more details on failed tests). Other notes are the settings buttons are not able to be unclicked and both can be simultaneously active when only one should be. Please make these changes along with the ones commented on the code.

2023-02-27 14:55 UTC, TristanPere commented on src/components/SettingsCard/SettingsCard.jsx
> +
white space

2023-02-27 14:55 UTC, TristanPere commented on src/components/SettingsCard/SettingsCard.jsx
> +
whitespace

2023-02-27 14:55 UTC, TristanPere commented on src/components/SettingsCard/SettingsCard.jsx
> +
whitespace

2023-02-27 14:55 UTC, TristanPere commented on src/components/SettingsCard/SettingsCard.test.js
> +  //arrange
Moving forward please remove comments in test file of act arrange assert.

2023-02-27 14:55 UTC, TristanPere commented on src/pages/Settings/Settings.jsx
> +
white space

2023-02-28 11:44 UTC, Joshua-Tucker commented
We've made our changes based on navcontainer / homebutton and layout media queries changing max-width to 767px.

2023-02-28 12:01 UTC, hannahmitchell99 requested changes

2023-02-28 12:01 UTC, hannahmitchell99 commented on src/components/SettingsCard/SettingsCard.jsx
> +
white space

2023-02-28 12:12 UTC, hannahmitchell99 approved these changes

2023-02-28 12:19 UTC, olirob93 approved these changes

2023-02-28 12:21 UTC, merged