Feature 67 edit resource page
nology-tech/Sable-client-project pull request #38
Opened 2023-02-27 14:58 UTC by BeckyRushton

Created edit resource and request resource pages, as well as creating form component. Tests completed for all and styling for responsiveness.

2023-02-27 16:44 UTC, TristanPere requested changes
Great form functionality, matches the figma perfectly with the addition of the extra input we talked about. Please make changes noted as well as address some weird styling issues at tablet display width

2023-02-27 16:44 UTC, TristanPere commented on src/components/Form/Form.scss
> +  .button {
Never call _.button_ as a styling convention as it restyles every appearance of a button. put your buttons in a named html container and style that.

2023-02-27 16:44 UTC, TristanPere commented on src/components/Form/Form.jsx
> +const Form = ({
Please call this something other than form as multiple forms are used and this isn't specific enough to this case. Same goes for file name.

2023-02-27 16:44 UTC, TristanPere commented on src/components/Form/Form.jsx
> +  });
Is this necessary to have a map for two options? cant we just right the options array?

2023-02-27 16:44 UTC, TristanPere commented on src/components/Form/Form.jsx
> +      <Button buttonText={text} />
please put a div around this for styling

2023-02-27 16:44 UTC, TristanPere commented on src/components/InputField/InputField.jsx
> +    const {label, placeholderText, id, handleInput, readOnly} = props
inline props please

2023-02-28 10:14 UTC, hannahmitchell99 requested changes
all looking great, just add in the separate array for the request resource page as discussed

2023-02-28 10:42 UTC, hannahmitchell99 approved these changes

2023-02-28 10:44 UTC, TristanPere approved these changes

2023-02-28 10:48 UTC, merged