Feature 77 static data refactor
nology-tech/Sable-client-project pull request #39
Opened 2023-02-27 16:12 UTC by tomas-trls

Created a large mock Data file, with more information, it can then be used through the whole application, including clients page etc.. 
:atom: :shipit:

2023-02-27 16:45 UTC, TristanPere requested changes
could you please add to the readme what each data item contains as keys else this is perfect

2023-02-28 09:44 UTC, hannahmitchell99 approved these changes

2023-02-28 09:44 UTC, olirob93 approved these changes

2023-02-28 09:50 UTC, TristanPere approved these changes

2023-02-28 09:51 UTC, merged