102 mockdata import refactor
nology-tech/Sable-client-project pull request #45
Opened 2023-03-01 10:29 UTC by DexterFreeman

Removed old mock data and changed imports so all the pages use the new mock data. 

Had to change the resource mockdata to add quantity and autopurchase level to it so that the datacard could access the information needed. May need to refactor the mockdata again as the resourcerequest data has information that it shouldn't: like the quantity of the resource as a whole, should only be how much of the resource that person has. Also each person seems to only request one resource.

2023-03-01 12:03 UTC, hannahmitchell99 requested changes

2023-03-01 12:03 UTC, hannahmitchell99 commented on src/containers/ResourcesOverview/ResourcesOverview.jsx
> +          <StaffResources cardsArray={resourceData}/>
line 11 can be removed and the mockData.resources import can be done directly on line 63. this is in the clients file too on line 10 and lines 41-44

2023-03-02 10:05 UTC, hannahmitchell99 approved these changes

2023-03-02 10:09 UTC, olirob93 approved these changes

2023-03-02 10:30 UTC, merged