Feature 26 book appointment submit button functionality
nology-tech/Sable-client-project pull request #46
Opened 2023-03-01 11:56 UTC by DexterFreeman

Added submit functionality and changed dropdownfield component so that the options render.

2023-03-01 15:44 UTC, hannahmitchell99 requested changes
looks amazing, just the changes to the props and adding some validation please

2023-03-01 15:44 UTC, hannahmitchell99 commented on src/components/DropdownField/DropdownField.jsx
> +  const JSX = options.map((option, index) => {
change props back as discussed

2023-03-02 11:17 UTC, hannahmitchell99 approved these changes

2023-03-02 11:19 UTC, olirob93 approved these changes

2023-03-02 11:19 UTC, merged