User Profile Card
nology-tech/Sable-client-project pull request #6
Opened 2023-02-20 15:06 UTC by BeckyRushton

Built staff card component and added styling to match example.

2023-02-20 16:51 UTC, TristanPere requested changes
Component is looking great, just like the one from figma! It needs some props so it can be modular dependent on given details (props). Also note points on not-yet-rendered components.

2023-02-20 16:51 UTC, TristanPere commented on src/components/UserProfileCard/UserProfileCard.jsx
> +const UserProfileCard = () => {
Currently takes no prompts so can't be changed when called. Would be great to take a staff name, type of employment, and image as prompts as well as any others you deem necessary

2023-02-20 16:51 UTC, TristanPere commented on src/pages/Home/Home.jsx
> +import UserProfileCard from "../../components/UserProfileCard/UserProfileCard";
Although you're working on it and it needs to be rendered to work on, when making a pull request only include items that need to be rendered at that time and place. I will go over this in the E.O.D. chat.

2023-02-20 16:51 UTC, TristanPere commented on src/pages/Home/Home.jsx
> +      <UserProfileCard />
Same comment as above

2023-02-21 09:44 UTC, olirob93 approved these changes

2023-02-21 09:44 UTC, TristanPere approved these changes

2023-02-21 09:51 UTC, merged